### ISSUE TITLE
Fail installing role openwisp.openwisp2

### ISSUE THREAD

**Issue by MDenti79** [openwisp/ansible-openwisp2#112]
Following the guide sending the command:
sudo ansible-galaxy install openwisp.openwisp2  -vvv --force
i'm getting this error:

ansible-galaxy 2.7.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/marco/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-galaxy
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
Using /etc/ansible/ansible.cfg as config file
Opened /home/marco/.ansible_galaxy
Processing role openwisp.openwisp2
- changing role openwisp.openwisp2 from 0.7.7 to unspecified
Opened /home/marco/.ansible_galaxy
- downloading role 'openwisp2', owned by openwisp
https://galaxy.ansible.com/api/v1/roles/?owner__username=openwisp&name=openwisp2
https://galaxy.ansible.com/api/v1/roles/14542/versions/?page_size=50
- downloading role from https://github.com/openwisp/ansible-openwisp2/archive/0.7.7.tar.gz
- extracting openwisp.openwisp2 to /home/marco/.ansible/roles/openwisp.openwisp2
- openwisp.openwisp2 (0.7.7) was installed successfully
- adding dependency: Stouts.postfix (origin/develop)
Processing role Stouts.postfix
ERROR! Unexpected Exception, this is probably a bug: sequence item 0: expected string, NoneType found
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-galaxy", line 118, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/dist-packages/ansible/cli/galaxy.py", line 162, in run
    self.execute()
  File "/usr/lib/python2.7/dist-packages/ansible/cli/__init__.py", line 155, in execute
    fn()
  File "/usr/lib/python2.7/dist-packages/ansible/cli/galaxy.py", line 398, in execute_install
    installed = role.install()
  File "/usr/lib/python2.7/dist-packages/ansible/galaxy/role.py", line 200, in install
    tmp_file = RoleRequirement.scm_archive_role(keep_scm_meta=self.options.keep_scm_meta, **self.spec)
  File "/usr/lib/python2.7/dist-packages/ansible/playbook/role/requirement.py", line 168, in scm_archive_role
    run_scm_cmd(clone_cmd, tempdir)
  File "/usr/lib/python2.7/dist-packages/ansible/playbook/role/requirement.py", line 150, in run_scm_cmd
    ran = " ".join(cmd)
TypeError: sequence item 0: expected string, NoneType found

**Comment by atb00ker** [comment]
Hi @MDenti79 ,

Thanks for reporting this, can please also let me know your distro? It will help me reproduce this error so that i can look into it. 

Thanks! :smile:

**Comment by MDenti79** [comment]
Hi @atb00ker ,
Now I'm using a clean installation of Ubuntu 16.04.5 LTS Desktop 64 bit.
I have also tried with Ubuntu 18.04.1 LTS and get same issue.
Thankyou

**Comment by nemesisdesign** [comment]
@MDenti79 that's strange, which part of the guide are you following exactly?
Could you share the `playbook.yml` and the commands you are running?

**Comment by nemesisdesign** [comment]
Closing for inactivity.
