### ISSUE TITLE
Server Error (500) when add/change devices or templates

### ISSUE THREAD

**Issue by mikysal78** [openwisp/ansible-openwisp2#225]
I check in in the /opt/openwisp2/log/ but I have not found error.
I testing on virtualbox with fresh install debian buster 64bit this playbook.

```yml
- hosts: openwisp2
  become: "{{ become | default('yes') }}"
  roles:
    - openwisp.openwisp2
  vars:
    openwisp2_default_from_email: "openwisp.basilicata@gmail.com"
    openwisp2_language_code: "it-it"
    openwisp2_time_zone: "UTC"
    openwisp2_ssl_state: "Italia"
    openwisp2_ssl_locality: "Matera"
    openwisp2_ssl_organization: "Ninux Basilicata"
    openwisp2_http_allowed_ip: "10.8.0.0/16"
  pre_tasks:
    - name: Install django-netjsonconfig
      pip:
        name: django-netjsonconfig
    - name: Creates temp directory ansible
      file:
        path: /var/www/.ansible/tmp
        state: directory
        owner: www-data
        group: www-data
        mode: 0777
        recurse: yes
    - debug:
        var: postfix_smtp_sasl_auth_enable
      tags: [postfix]
```

i see the merged  [[change!] Removed django-netjsonconfig](https://github.com/openwisp/ansible-openwisp2/commit/6b170edbc4891800b68bdccc1910a4ec9741d5a5) and i try restore snapshot and comment pretask...
there is an error:

```bash
TASK [openwisp.openwisp2 : migrate] *******************************************************************************************************************************************************************************
Sunday 29 November 2020  09:48:03 +0100 (0:00:00.845)       0:02:57.151 ******* 
fatal: [openwisp.vbox]: FAILED! => changed=false 
  cmd: ./manage.py migrate --noinput
  msg: |2-
  
    :stderr: Traceback (most recent call last):
      File "./manage.py", line 10, in <module>
        execute_from_command_line(sys.argv)
      File "/opt/openwisp2/env/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
        utility.execute()
      File "/opt/openwisp2/env/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/opt/openwisp2/env/lib/python3.7/site-packages/django/core/management/base.py", line 330, in run_from_argv
        self.execute(*args, **cmd_options)
      File "/opt/openwisp2/env/lib/python3.7/site-packages/django/core/management/base.py", line 371, in execute
        output = self.handle(*args, **options)
      File "/opt/openwisp2/env/lib/python3.7/site-packages/django/core/management/base.py", line 85, in wrapped
        res = handle_func(*args, **kwargs)
      File "/opt/openwisp2/env/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 75, in handle
        self.check(databases=[database])
      File "/opt/openwisp2/env/lib/python3.7/site-packages/django/core/management/base.py", line 396, in check
        databases=databases,
      File "/opt/openwisp2/env/lib/python3.7/site-packages/django/core/checks/registry.py", line 70, in run_checks
        new_errors = check(app_configs=app_configs, databases=databases)
      File "/opt/openwisp2/env/lib/python3.7/site-packages/django/contrib/staticfiles/checks.py", line 7, in check_finders
        for finder in get_finders():
      File "/opt/openwisp2/env/lib/python3.7/site-packages/django/contrib/staticfiles/finders.py", line 282, in get_finders
        yield get_finder(finder_path)
      File "/opt/openwisp2/env/lib/python3.7/site-packages/django/contrib/staticfiles/finders.py", line 295, in get_finder
        return Finder()
      File "/opt/openwisp2/env/lib/python3.7/site-packages/openwisp_utils/staticfiles.py", line 23, in __init__
        module = importlib.import_module(dependency)
      File "/opt/openwisp2/env/lib/python3.7/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
      File "<frozen importlib._bootstrap>", line 983, in _find_and_load
      File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'django_netjsonconfig'
  path: /opt/openwisp2/env/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  syspath:
  - /tmp/ansible_django_manage_payload_voal7874/ansible_django_manage_payload.zip
  - /usr/lib/python37.zip
  - /usr/lib/python3.7
  - /usr/lib/python3.7/lib-dynload
  - /usr/local/lib/python3.7/dist-packages
  - /usr/lib/python3/dist-packages
```
ModuleNotFoundError: No module named 'django_netjsonconfig'

how can i fix Server Error (500)?
thanks

**Comment by mikysal78** [comment]
Change old versione controller.
Add  vars openwisp2_controller_version: "0.7.0" it's ok.
