### ISSUE TITLE
[bug] Build failures for bpython installation

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/ansible-openwisp2#263]
Some builds in https://github.com/openwisp/ansible-openwisp2/pull/223 and https://github.com/openwisp/ansible-openwisp2/pull/262 are failing with errors like:

```
fatal: [openwisp2-ubuntu1804]: FAILED! => changed=false 
    attempts: 5
    cmd:
    - /opt/openwisp2/env/bin/pip3
    - install
    - -U
    - bpython
    msg: |-
      stdout: Collecting bpython
        Using cached bpython-0.21-py3-none-any.whl (180 kB)
      Collecting pyxdg
        Using cached pyxdg-0.27-py2.py3-none-any.whl (49 kB)
      Collecting curtsies>=0.3.5
        Using cached curtsies-0.3.5.tar.gz (53 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'error'
    
      :stderr:   ERROR: Command errored out with exit status 1:
         command: /opt/openwisp2/env/bin/python3 /opt/openwisp2/env/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp5dokmy46
             cwd: /tmp/pip-install-n2_olv9_/curtsies
        Complete output (10 lines):
        Traceback (most recent call last):
          File "/opt/openwisp2/env/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
            main()
          File "/opt/openwisp2/env/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
          File "/opt/openwisp2/env/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 108, in get_requires_for_build_wheel
            backend = _build_backend()
          File "/opt/openwisp2/env/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 99, in _build_backend
            obj = getattr(obj, path_part)
        AttributeError: module 'setuptools.build_meta' has no attribute '__legacy__'
        ----------------------------------------
      ERROR: Command errored out with exit status 1: /opt/openwisp2/env/bin/python3 /opt/openwisp2/env/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp5dokmy46 Check the logs for full command output.
      WARNING: You are using pip version 20.2.4; however, version 21.0.1 is available.
      You should consider upgrading via the '/opt/openwisp2/env/bin/python3 -m pip install --upgrade pip' command.
```

**Comment by rschwebel** [comment]
I've just seen this on Debian Bullseye.

**Comment by nemesisdesign** [comment]
> I've just seen this on Debian Bullseye.

@rschwebel have you tried deploying the [upcoming version of OpenWISP (2022)](https://github.com/openwisp/ansible-openwisp2#deploying-the-upcoming-release-of-openwisp)? It's almost ready for release but we're working on fixing some remaining issues which need backward incompatible changes, but if you're starting out now it's better to use that.
