### ISSUE TITLE
[OpenWisp Radius] Server Error 500

### ISSUE THREAD

**Issue by mikysal78** [openwisp/ansible-openwisp2#360]
I try add "batch user creation", select prefix, etc.. 
Click to save and i have Server Error 500
In the log /opt/openwisp2/log/openwisp2.log see this error:

```
[ERROR 2022-03-31 22:33:26,139] module: log, process: 180900, thread: 139885627688768
Internal Server Error: /admin/openwisp_radius/radiusbatch/add/
Traceback (most recent call last):
  File "/opt/openwisp2/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/openwisp2/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/openwisp2/env/lib/python3.9/site-packages/django/contrib/admin/options.py", line 683, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/opt/openwisp2/env/lib/python3.9/site-packages/django/utils/decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/opt/openwisp2/env/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/opt/openwisp2/env/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/opt/openwisp2/env/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1885, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/opt/openwisp2/env/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/opt/openwisp2/env/lib/python3.9/site-packages/django/utils/decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/opt/openwisp2/env/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1745, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/opt/openwisp2/env/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1797, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "/opt/openwisp2/env/lib/python3.9/site-packages/openwisp_radius/admin.py", line 445, in save_model
    obj.prefix_add(prefix, n)
  File "/opt/openwisp2/env/lib/python3.9/site-packages/openwisp_radius/base/models.py", line 975, in prefix_add
    user.full_clean()
  File "/opt/openwisp2/env/lib/python3.9/site-packages/django/db/models/base.py", line 1405, in full_clean
    raise ValidationError(errors)
django.core.exceptions.ValidationError: {'language': ["Il valore 'it-it' non è una scelta valida."]}
[WARNING 2022-03-31 22:33:26,376] module: log, process: 180900, thread: 139885627688768
Not Found: /robots.txt

[WARNING 2022-03-31 22:33:26,636] module: log, process: 180900, thread: 139885627688768
Not Found: /favicon.ico

[WARNING 2022-03-31 22:33:27,661] module: log, process: 180900, thread: 139885627688768
Not Found: /favicon.ico
```

**Comment by nemesisdesign** [comment]
Change `openwisp2_language_code` in your playbook to just `openwisp2_language_code: it`.
This is not a bug report, please use the support channels for these support requests.
